### PR TITLE
Rename crypto_rand.rs to rand.rs in crypto and other crates

### LINKED ISSUE #210: offst-crypto: Rename crypto_rand.rs to rand.rs
`crypto_rand.rs` is an unfortunate choice of name for the random utils module inside `offst-crypto` crate.

For example, this is what current imports look like:
```rust
use crypto::crypto_rand::{CryptoRandom, RandValue};
```

A better name for this module might be just `rand`, which should result in imports of this form:

```rust
use crypto::rand::{CryptoRandom, RandValue};
```

The crypto crate is used in most of offst crates. I suggest to begin with modifying the lowest crates first: `offst-common` and `offst-proto`, and only then move on to the rest of the crates.

At any time, running `cargo test` should show any failures during the renaming. The more specific `cargo test -p offst-XYZ` allows to test a specific crate (Given that all dependencies compile too).

This issue does not require great familiarity with the Offst project, and I think it can be solved by Rust beginners too. Guidance will be given to anyone who wants to solve this. Please send a message if you plan to work on this issue.

### PR DESCRIPTION
**Pull request by Atul9**
closes #210

### CODE REVIEW

**Comment by Atul9** [comment]
@realcr does this https://travis-ci.com/freedomlayer/offst/jobs/206612603 build fail since `cargo-sweep` already exists in destination`? Please suggest what changes can I make to get the build pass.

**Comment by pzmarzly** [comment]
No, it fails at `cargo fmt`. Just run `cargo fmt` and make a commit.

`cargo-sweep` is just a warning, though that's not clear at the first glance. I will change that.

**Comment by Atul9** [comment]
@pzmarzly @realcr I have updated the PR, please review.

**Comment by realcr** [comment]
@pzmarzly : Thanks for helping out!

@Atul9 : Thank you for your contribution, highly appreciated!
One thing that can be useful in the future: Offst is a project with multiple crates. I think that if you run `cargo fmt` from the root directory it can fix the formatting in all crates at once. I also believe it is reasonable to have just a single commit for running `cargo fmt` for the whole project.

**Pull request merged**
