### PR TITLE
Have rust version pinned in a single place

### LINKED ISSUE #209: Having rust nightly version pinned in a single place
We currently have the pinned rust nightly version in use scattered in a few places.
(1) The file: `rust-toolchain` (See here: https://github.com/rust-lang/rustup.rs#the-toolchain-file)
(2) .travis.yml contains the used nightly version in three places (See snippet below).

This means that every time we bump rust nightly's version we have to modify all those places at the same time. Is it somehow possible for us to make .travis.yml find the pinned rust nightly version from the `rust-toolchain` file automatically?

Snippet from `.travis.yml` (Containing rust nightly version 3 times):

```yaml
  - env: TARGET=x86_64-unknown-linux-gnu CC=gcc-6 CXX=g++-6 RUSTFLAGS="-C link-dead-code"
    os: linux
    dist: trusty
    rust: nightly-2019-06-07
    addons:
      apt:
        packages:
        - gcc-6
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    script:
    - travis/trusty/pre/cargo-config.sh
    - travis/trusty/pre/capnp.sh
    - cargo fmt --all -- --check
      # TODO: Enable these two lints when clippy bugs are solved:
    - cargo clippy -- -A clippy::needless_lifetimes -A clippy::identity_conversion
      # We add target dir so that kcov can find the test files to run:
    - cargo test --target ${TARGET}
    - travis/trusty/post/kcov/try-install.sh
    - travis/trusty/post/kcov/run.sh

  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly-2019-06-07
    osx_image: xcode9.4.1
    before_script:
    - brew install capnp
    script:
    - cargo test

  - env: TARGET=x86_64-pc-windows-msvc
    os: windows
    # Used as a temporary fix for windows CI issue in travis.
    # See: https://travis-ci.community/t/windows-instances-hanging-before-install/250/25
    filter_secrets: false
    rust: nightly-2019-06-07
    ...
```

EDIT: See: https://github.com/travis-ci/travis-build/pull/1513

### PR DESCRIPTION
**Pull request by pzmarzly**
Closes #209 

Currently I'm waiting for CI, I'll remove the `[WIP]` once I'm sure it can be merged.

### CODE REVIEW

**Comment by pzmarzly** [comment]
I think #221 and #214 could be merged, hopefully there won't be any conflicts.

**Comment by realcr** [comment]
Merged. Great fix! thanks.

**Comment by haposan** [comment]
Hi Guys,

I just revisit the Offst project.
I need help to run the application.
Thanks.

**Comment by realcr** [comment]
@haposan: Hi, what's up? Thanks for visiting!
First - note that your message ended up inside the discussion of a closed pull request. This is a pretty unfortunate place to write a question, because there is a danger it will go unnoticed. Usually a better place to send questions or issues is at the issues page, here: https://github.com/freedomlayer/offst/issues

About how to run Offst: You can get some instructions about how to run the first release here:
https://www.freedomlayer.org/offst/offst-release/
However, my advice for you is to wait a bit. We are working on releasing the next version which implements a new protocol (That is incompatible with the previous release). It should also include an easier to use client, hopefully with GUI, which should be more fun to use than the current command line based client. You can subscribe to the mailing list at freedomlayer.org, and you will get a notice when the next release is ready.

**Comment by haposan** [comment]
@real: thanks for the advice and info.
@everyone : sorry to post the question at wrong channel.
I'm trying to familiarize my self with the Offst implementation and infrastructure.
It has a unique concept.
Hopefully I can start contributing early next month. 
@everyone, please let me know what possible roles I might be able to contribute. 
I'm a developer (using c/c++ and Java) and just learn Rust. 
Please be easy on me 😁🙏. 


Regards,
Haposan

**Comment by realcr** [comment]
@haposan: Thank you for offering your help!
I hope to be able to prepare you something interesting to do when you have the time.
The most up to date document about how Offst works internally is the "atomic payments redesign", which can be found here:
https://github.com/freedomlayer/offst/blob/master/doc/docs/atomic_proposal.md

This part mostly documents the `offst-funder` crate. Unfortunately the rest of Offst is currently less documented. Things are still changing often.

After reading this document, the next thing you can do is trying to make the repository compile on your machine. You can find instructions about how to do this here: https://github.com/freedomlayer/offst/blob/master/README.md

If you don't understand something or something doesn't work for you, don't hesitate to open an issue.

**Pull request merged**
